### ISSUE TITLE
App hasn't worked for a few days

### ISSUE THREAD

**Issue by Vallenesca** [malclocke/ChristchurchMetro#4]
App now shows all bus stops as "unable to retrieve information" and when looking at stops not in your saved list it comes up blank for the stop itself. I suspect it might have something to do with Metroinfo changing their website, but I'm unsure. 

There's a few one star reviews happening on google dating back to October 20th. I made this account in hopes to contact ya here to let you know about it

**Comment by malclocke** [comment]
Thanks @Vallenesca.  Metro have turned off the old data feed that the app uses so it's no longer working.  I'm working on an update but it may be a week or two before it's ready.

In the meantime you could try the next bus feature on the metro website at https://go.metroinfo.co.nz/mtbp/en-gb/arrivals/content/nearby

**Comment by Vallenesca** [comment]
I have been, wasnt sure if you knew about the change hence why I contacted you. I'm a regular user of the app myself.

**Comment by Vallenesca** [comment]
Still no luck on updating?

**Comment by malclocke** [comment]
Metro got in touch with me unhappy that they keep getting contacted by people thinking the app is official.  They asked that I either pull the app from the store or if I am going to update to change the app name and branding so it is obvious that it is not an official app.

Unfortunately this means I need to do a lot more work than just updating the data feed, and I've decided to pull the app as a consequence.  Thanks for raising the issue here, sorry the app won't be getting another update :disappointed:
